### ISSUE TITLE
Which VIT weights are you adapted to train your released model?

### ISSUE THREAD

**Issue by XiongweiWu** [amzn/image-to-recipe-transformers#1]
Hi, can u tell me which VIT weights are you using for your released model ? I notice in rwightman's repository there are two versions of VIT pre-trained weights (vit_base_p16_224-4e355ebd.pth before Oct 30th, and jx_vit_base_p16_224-80ecf9dd.pth after Oct 30th). I guess the released model may be based on the first one since it's before the CVPR ddl, but I just make a confirm from your side.

**Comment by amaiasalvador** [comment]
The released models were trained for the code release (after submission), thus we initialized ViT using the latest version of the pretrained weights: ```jx_vit_base_p16_224-80ecf9dd.pth```.
